name: Generate chart for profile

on:
  schedule:
    - cron: 10 04 * * THU

jobs:
  chart:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Configure Git
        run: |
          git config --global user.email "apwheele@gmail.com"
          git config --global user.name "apwheele"
          git pull
      - name: Pothole Plot
        run: |
          python -m pip install --user --upgrade build
          pip install pandas numpy matplotlib requests
          python potholes.py
      - name: Commit and push
        run: |
          git add PH_Ral_Week.png
          git commit -m 'Regenerated weekly chart'
          git push
      - run: echo "🍏 This job's status is ${{ job.status }}."

