# Updating repo
#   schedule:
#    - cron: 10 11 * * THU


name: Generate chart for profile

on:
  push:
    branches:
      - main
      - master

jobs:
  chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python and Platform version
        run: python -c "import sys; print(sys.version); print(sys.platform)"
      - name: Install dependencies simple check
        run: |
          python -m pip install --user --upgrade build
          pip install pandas numpy matplotlib
          python potholes.py
      - name: Configure Git
        run: |
          git config --global user.email "apwheele@gmail.com"
          git config --global user.name "apwheele"
      - name: Commit and push if changed
        run: |
          set -e
          set -x
          git add PH_Ral_Week.png
          git commit -m 'Regenerated weekly chart'
          git push
      - run: echo "🍏 This job's status is ${{ job.status }}."

