name: Generate Dallas Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: 21 09 * * TUE

jobs:
  chart:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip
      - name: Install pandas
        run: |
          python -m pip install --user --upgrade build
          pip install -r requirements.txt
      - name: Create Dallas Data
        run: |
          python dallas_data.py
      - name: Configure Git
        run: |
          git config --global user.email "apwheele@gmail.com"
          git config --global user.name "apwheele"
      - name: Commit and push
        run: |
          git pull
          git add dallasdata.parquet.gzip
          git commit -m 'Dallas weekly data run'
          git push
      - run: echo "🍏 This job's status is ${{ job.status }}."

