name: Generate Dallas Data

on:
  schedule:
    - cron: 21 09 * * *
  push:
    paths:
      - 'dallas_data.py'

jobs:
  chart:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install pandas
        run: |
          python -m pip install --user --upgrade build
          pip install -r requirements.txt
      - name: Configure Git
        run: |
          git config --global user.email "apwheele@gmail.com"
          git config --global user.name "apwheele"
          git pull
      - name: Create Dallas Data
        run: |
          python dallas_data.py
      - name: Commit and push
        run: |
          git add dallasdata.csv.zip
          git commit -m 'Dallas weekly data run'
          git push
      - run: echo "🍏 This job's status is ${{ job.status }}."

